[libraries]
# Redis
jedis = { module = "redis.clients:jedis", version = "4.4.0-m1" }

# Utils
lombok = { module = "org.projectlombok:lombok", version = "1.18.26" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }
gson = { module = "com.google.code.gson:gson", version = "2.8.8" }
reflections = { module = "org.reflections:reflections", version = "0.10.2" }

# LightDream
lightdream_logger = { module = "dev.lightdream:logger", version = "3.2.4" }
lightdream_lambda = { module = "dev.lightdream:lambda", version = "4.0.0" }
lightdream_messagebuilder = { module = "dev.lightdream:message-builder", version = "3.1.2" }
